CHANGELOG.md, DEVELOP.md, README.md, lonboard/serialization.py, lonboard/traits.py, lonboard/viz.py, package-lock.json, package.json, pyproject.toml
🚀 
- Fix default color to be black, not white
- quick start in initial readme to use `viz`
- Lower arrow chunk size to 5MB
- Fix `viz` missing a table param (`table` is keyword only)
- Document that docs publishing happens on CI
- Add initial changelog
- Bump version to 0.1
Any other changes from here will be docs/example updates
=> Fixes for 0.1

CHANGELOG.md, pyproject.toml, src/parquet.ts, src/path-layer.tsx, src/solid-polygon-layer.tsx
Update version and changelog and publish
=> Bump version and cleanup

CHANGELOG.md, package-lock.json, package.json, pyproject.toml
Also bump tag and update changelog
=> actually bump deck.gl layers to 0.2.0 😅 

README.md
=> fix viz link

docs/performance.md
Closes https://github.com/developmentseed/lonboard/issues/130
=> Update performance advice

src/tooltip/index.ts
Before:
https://github.com/developmentseed/lonboard/assets/15164633/b5819bea-f8a9-41e7-b957-53044724b0a5
After:
https://github.com/developmentseed/lonboard/assets/15164633/3925de0a-88c5-402e-9c6c-cf1ea914399d
=> Fix tooltip when row is not found

lonboard/traits.py, tests/test_traits.py
Closes https://github.com/developmentseed/lonboard/issues/71
=> Improved validation error messages

.github/workflows/deploy-mkdocs.yml, docs/overrides/main.html, mkdocs.yml, poetry.lock, pyproject.toml
This is kinda tough to get working, and without testing in prod 🤷‍♂️ 
When I run this locally, it ignores my gitignore and tries to push all of `node_modules`, `.cache`, etc to the branch
=> Try to add versioned docs

lonboard/_layer.py, tests/test_layer.py
Closes https://github.com/developmentseed/lonboard/issues/127
=> Simplify accessor validation

lonboard/_layer.py, src/model.ts
- Adds `visible`, `opacity`, and `auto_highlight` to the base layer
=> More base layer props

examples/integrations/color-picker.ipynb, examples/integrations/sidecar.ipynb, examples/internet-speeds.ipynb, examples/north-america-roads.ipynb
- Update notebooks to use 0.2 API
=> Update notebooks for 0.2 API

docs/api/layers/path-layer.md, docs/api/layers/scatterplot-layer.md, docs/api/layers/solid-polygon-layer.md, docs/api/map.md, examples/integrations/sidecar.ipynb, lonboard/_map.py, mkdocs.yml, src/index.tsx
- Add `_height` attribute to the `Map` object.
- Docstring for `_height` and `_initial_view_state`
- Add `Map` docs page
Supersedes https://github.com/developmentseed/lonboard/pull/165
Workaround for https://github.com/developmentseed/lonboard/issues/167
=> Adjust map height

lonboard/_map.py, src/index.tsx
- Adds `show_tooltip` to the `Map` object
=> Allow hiding tooltip

.github/workflows/deploy-mkdocs.yml
Fix docs publish starting with `v`
=> fix docs publish

.gitignore, build.mjs, lonboard/_map.py
Closes https://github.com/developmentseed/lonboard/issues/8, many, many thanks to @manzt in https://github.com/manzt/anywidget/issues/369#issuecomment-1792376003 🙇. This turned out to be stupid easy, I still can't believe it.
=> Save widget to standalone HTML file

lonboard/traits.py, tests/test_traits.py
Closes https://github.com/developmentseed/lonboard/issues/190
=> Allow pandas series as accessor to FloatAccessor

pyproject.toml
=> Actually bump to 0.3

lonboard/__init__.py, lonboard/_layer.py, package-lock.json, package.json, src/index.tsx, src/model.ts
Working heatmap layer:
https://github.com/developmentseed/lonboard/assets/15164633/20bb0c06-b72e-4783-80ed-dfb48ec21d67
Note that this rechunks (actually, I should check the pyarrow api to see whether this forces a rechunk to a single chunk or just doesn't rechunk to smaller chunks), because by default, we render each chunk of data on the frontend independently, and then it looks weird (though cool!) on the frontend:
https://github.com/developmentseed/lonboard/assets/15164633/4b669c10-8eff-4105-a65b-0e3bb0db93fa
=> Add HeatmapLayer

CHANGELOG.md, package-lock.json, package.json, pyproject.toml
- Bump deck.gl-layers to include https://github.com/geoarrow/deck.gl-layers/pull/74
- Bump version
- Update changelog
Closes https://github.com/developmentseed/lonboard/issues/241
=> Fix polygon rendering

CHANGELOG.md, package-lock.json, package.json, pyproject.toml
=> Bump deck.gl/layers

lonboard/_layer.py, src/model/layer.ts
Closes https://github.com/developmentseed/lonboard/issues/134
=> Sync the clicked index back to Python

lonboard/_layer.py
for https://github.com/developmentseed/lonboard/issues/275
=> Set `width_min_pixels` in PathLayer example

docs/api/layers/bitmap-layer.md, docs/api/layers/bitmap-tile-layer.md, lonboard/__init__.py, lonboard/_layer.py, lonboard/_map.py, src/model/layer.ts
Continuation of https://github.com/developmentseed/lonboard/pull/285, closes https://github.com/developmentseed/lonboard/issues/206, closes #285
=> bitmap and bitmap tile layer

lonboard/colormap.py
Closes https://github.com/developmentseed/lonboard/issues/263
=> accept matplotlib colormap input to apply_cmap

lonboard/_layer.py
Ref https://github.com/openstreetmap/operations/issues/737
=> Use preferred OSM tile url

README.md
Closes https://github.com/developmentseed/lonboard/pull/226
=> add reference for installing from source

build.mjs, src/index.tsx, tsconfig.json
Slightly simpler revision of #344 that was pointed out on discord
=> Bump to es2022 and use top-level await

mkdocs.yml
- [Default](?expand=1&template=default.md)
- [Version Release](?expand=1&template=version_release.md)
- _Alternatively delete and start empty_
=> docs fixes

lonboard/controls.py
Ref https://github.com/developmentseed/lonboard/issues/363#issuecomment-1943616456
=> Raise error on single input to MultiRangeSlider

lonboard/_geoarrow/ops/reproject.py
Lonboard currently throws an exception on the input data from the latest main of geoarrow-rs because it exposes metadata of the type `{"crs": null, "edges": null}`, and we were trying to construct `CRS(None)`.
=> Allow non-compliant geoarrow CRS metadata

package-lock.json, package.json
Includes the fix here: https://github.com/geoarrow/deck.gl-layers/pull/108
Closes https://github.com/developmentseed/lonboard/issues/378
=> Fix viewing polygons in local html files

.github/ISSUE_TEMPLATE/bug---a-user-discovered-bug.md
=> add missing about property

lonboard/_map.py, lonboard/_viz.py
This also improves the CLI UX as features aren't just _black_. The CLI is really usable now; like [mbview](https://github.com/mapbox/mbview) but without a local server running.
https://github.com/developmentseed/lonboard/assets/15164633/22d94dab-6dd8-464e-a248-7f142a438730
Closes https://github.com/developmentseed/lonboard/issues/380, closes https://github.com/developmentseed/lonboard/issues/281
=> Improve default colors in `viz`

lonboard/_geoarrow/ops/reproject.py, tests/test_layer.py
Closes https://github.com/developmentseed/lonboard/issues/371
=> Warn on missing CRS

docs/api/colormap.md, docs/api/layers/point-cloud-layer.md, lonboard/__init__.py, lonboard/_layer.py, lonboard/traits.py, mkdocs.yml, package-lock.json, package.json, src/model/layer.ts, tests/test_layer.py
=> Add PointCloudLayer

lonboard/_map.py, lonboard/types/map.py, src/actions/fly-to.ts, src/index.tsx, src/types.ts
- Add `Map.fly_to` which "flies" map to desired view state location
=> Add fly-to map action

MANIFEST.in, pyproject.toml
For https://github.com/conda-forge/lonboard-feedstock/pull/10
=> Conda: Try including `manifest.in` file for `static` folder inclusion

lonboard/_viz.py, tests/test_viz.py
Closes https://github.com/developmentseed/lonboard/issues/424
=> Fix `viz()` with `__geo_interface__` input

lonboard/_viz.py
=> Fix viz docstring

poetry.lock, pyproject.toml
=> bump development version of geoarrow-rust-core

poetry.lock
Bump to fix https://github.com/squidfunk/mkdocs-material/issues/6983. Should fix https://github.com/developmentseed/lonboard/issues/459
=> Bump mkdocs-material

docs/overrides/partials/integrations/analytics/plausible.html, mkdocs.yml
Closes https://github.com/developmentseed/lonboard/issues/463
=> Add plausible integration

docs/overrides/partials/integrations/analytics/plausible.html, mkdocs.yml
=> Add feedback option to each docs page using plausible

examples/index.md, mkdocs.yml
- [Default](?expand=1&template=default.md)
- [Version Release](?expand=1&template=version_release.md)
- _Alternatively delete and start empty_
=> Add overture example page to TOC

docs/api/layer-extensions/path-style-extension.md, docs/api/traits.md, lonboard/layer_extension.py, lonboard/traits.py, mkdocs.yml, src/model/extension.ts, src/model/index.ts, tests/test_traits.py
I've done a very basic addition of `PathStyleExtension` to address #484. One key TODO is checking the accessor for `get_dash_array`. I've noted it in the class doc. 
This is my first PR so I'm not sure if I've missed anything. Let me know! 😄
=> Adding PathStyleExtension code

CHANGELOG.md, examples/duckdb.ipynb, pyproject.toml
- Update changelog
- Fix link
- Bump to 0.9
=> Bump to 0.9 and add changelog

lonboard/_map.py
Closes https://github.com/developmentseed/lonboard/issues/518
=> Add type checks to fly_to

CHANGELOG.md, pyproject.toml
Update changelog and bump version
=> Bump to 0.9.2

lonboard/_geoarrow/ops/reproject.py
Closes https://github.com/developmentseed/lonboard/issues/528
When GeoPandas 1.0 is out, we should add a test for this. Ref https://github.com/developmentseed/lonboard/issues/533
=> Fix reprojecting GeoArrow input

CHANGELOG.md, pyproject.toml
Includes https://github.com/developmentseed/lonboard/pull/532
=> Bump to 0.9.3

poetry.lock, pyproject.toml
Closes https://github.com/developmentseed/lonboard/issues/553
=> Move docs dependencies to docs group

.github/workflows/test.yml
Closes https://github.com/developmentseed/lonboard/issues/554
=> Add CI check to ensure docs build without warnings

.env.example, DEVELOP.md
This adds some documentation about the use of environment variables and XState in the JavaScript component.
@kylebarron @batpad while XState is becoming increasingly popular, some JS devs might not be familiar with it. I tried to add basic instructions on how to develop with it. Please let me know if you have questions or suggestions on how to improve the developer documentation.
=> Documentation about environment variables and XState

lonboard/_serialization.py, poetry.lock, pyproject.toml
- Update to arro3 0.2.1
- Enable rechunking table before saving.
=> Re-enable chunking when saving to Parquet

poetry.lock, pyproject.toml
- We rely on numpy but I don't think any current dependency itself requires numpy
- anywidget may remove its ipywidgets dependency in the future
=> Add explicit numpy, ipywidgets dependency

lonboard/_compat.py, tests/compat.py, tests/test_cli.py, tests/test_layer.py, tests/test_viz.py
Also remove dependency on `packaging`
=> mostly remove compat file from public package

poetry.lock, pyproject.toml
=> Bump to 0.10.0-beta.1

lonboard/layer_extension.py, src/model/extension.ts
https://github.com/user-attachments/assets/dd19ef17-0588-410a-a14e-0eb775100da9
=> Basic categorical data filter

lonboard/_viz.py
Instead of randomly shuffling the list of colors each time, keep a global counter for the index into the list.
=> Use deterministic colors in `viz`

lonboard/_layer.py, lonboard/_viz.py, poetry.lock, pyproject.toml, tests/test_duckdb.py
Closes https://github.com/developmentseed/lonboard/issues/622
=> Add test for duckdb table with no property columns

lonboard/_geoarrow/_duckdb.py, tests/test_duckdb.py
Follow up for #623  and #622, based on input from https://github.com/developmentseed/lonboard/discussions/619#discussioncomment-10536974
=> Fix reading from DuckDB with only geometry column

lonboard/_geoarrow/crs.py, lonboard/_geoarrow/extension_types.py, lonboard/_geoarrow/geopandas_interop.py, lonboard/_geoarrow/parse_wkb.py, tests/test_geoarrow.py
Closes https://github.com/developmentseed/lonboard/issues/641
=> Avoid double-stringify of CRS

lonboard/_geoarrow/ops/reproject.py
Closes https://github.com/developmentseed/lonboard/issues/566
=> Update reprojection warning

lonboard/_layer.py, src/model/base-layer.ts
Closes https://github.com/developmentseed/lonboard/issues/661
=> Add `highlight_color`

CHANGELOG.md, lonboard/_geoarrow/movingpandas_interop.py, pyproject.toml
=> Don't use `np.alltrue`, bump to 0.10.2

CHANGELOG.md, pyproject.toml
Includes https://github.com/developmentseed/lonboard/pull/731 for https://github.com/developmentseed/lonboard/issues/725
=> Bump to 0.10.4

.github/workflows/conventional-commits.yml
https://www.conventionalcommits.org/en/v1.0.0/
ref https://github.com/geoarrow/geoarrow-rs/pull/1144
=> ci: Enforce conventional commits

DEVELOP.md
=> chore: Suggest shallow clone of repo in DEVELOP.md

lonboard/_geoarrow/extension_types.py, lonboard/_geoarrow/parse_wkb.py, pyproject.toml
Mostly about setting a variable back to a name that had a different type
=> chore: Fix mypy lint errors

examples/migration.ipynb, lonboard/experimental/_layer.py, lonboard/traits.py
ArcLayer doesn't require geometry column in the table
Closes https://github.com/developmentseed/lonboard/issues/756
=> fix(arc-layer): Fix migration example

lonboard/__init__.py, lonboard/experimental/__init__.py
Closes https://github.com/developmentseed/lonboard/issues/868
=> fix: Add `__all__` declarations to modules to fix pylance warnings
