developmentseed/lonboard

lonboard/traits.py

This was just added in a very recent traitlets version, and so isn't available e.g. with the default binder traitlets version

don't use generic typing in TraitType

---

.github/workflows/release.yml
DEVELOP.md
README.md
pyproject.toml

The current release is broken because the JS files are never built.
- Build js files in CI
- Check that files exist in the wheel with a path of `lonboard/static`

fix release

---

package-lock.json
package.json
src/parquet.ts

Note: this is blocked on me having fast enough internet (not on a train) to publish parquet-wasm 0.5 and test this.
Closes https://github.com/developmentseed/lonboard/issues/91, Closes https://github.com/developmentseed/lonboard/issues/68

bump deck.gl-layers and parquet-wasm

---

lonboard/traits.py
tests/test_traits.py

- Allow passing a hex string like `#fff`
- Add tests
For #7

Allow hex string color input to ColorAccessor

---

.github/workflows/deploy-mkdocs.yml

Otherwise, the docs will reflect _main_ rather than the latest release

Don't publish docs on every PR

---

poetry.lock
pyproject.toml

We use ruff format ourselves, but mkdocstrings requires black to be installed to format signatures in the docs

Restore black as dev dependency

---

docs/api/layers/path-layer.md
docs/api/layers/scatterplot-layer.md
docs/api/layers/solid-polygon-layer.md
lonboard/_layer.py
src/model.ts

- Move `_rows_per_chunk` and `from_geopandas` to the `BaseLayer` class.
- Add `pickable` boolean option (defaulting to `True`) to the base `BaseLayer` class, use `pickable` on the JS side to control layer interactivity.
- Render inherited members in the docs

Deduplicate layer props

---

lonboard/_geoarrow/ops/centroid.py
lonboard/_layer.py
lonboard/_map.py
lonboard/_viewport.py

- Update centroid and bbox helpers to take in an array of geoarrow tables.
- Move `initial_view_state` default function to `Map` class

Restore inferring initial view state from data

---

poetry.lock
pyproject.toml

This was needed back when we were using the `experimental` module within anywidget

Remove comm dependency

---

lonboard/_layer.py
lonboard/_utils.py

Closes https://github.com/developmentseed/lonboard/issues/194

Automatically downcast data types in `from_geopandas`

---

poetry.lock
pyproject.toml

For https://github.com/developmentseed/lonboard/issues/224#event-10923390427
We currently assume the pandas version is >=2.
For now, we can set a pandas 2.0 requirement, but in the long term, pandas and geopandas will be optional dependencies. Maybe we conditionally import pandas and only use `dtype_backend` if the pandas version is >=2?

Add pandas v2 requirement

---

.github/workflows/test.yml
poetry.lock
pyproject.toml

Make sure we don't install watchfiles on ci. Ref https://github.com/manzt/anywidget/issues/374

Add watchfiles to separate dependency group

---

docs/api/colormap.md
lonboard/colormap.py
tests/test_colormap.py

- Add a function `apply_categorical_cmap` that applies colors from a categorical column.
This is 180-200x faster than leafmap's existing `assign_discrete_colors` method on string data. When the user already has their data stored as a categorical, it's 620x faster than leafmap (although leafmap seemed to crash on the categorical I tested, so that's comparing `apply_categorical_cmap` on the categorical with `assign_discrete_colors` on the string). 
On the [dc wetlands dataset](https://data.source.coop/giswqs/nwi/wetlands/DC_Wetlands.parquet) with 1500 rows:
Expanding the rows 1000 times to test with 1.5 million rows:
And when the input column is already a pandas categorical, this drops to 25ms.

Add method to apply a categorical colormap

---

lonboard/_constants.py
lonboard/_environment.py
lonboard/_map.py

Closes https://github.com/developmentseed/lonboard/issues/249. 
The goal is for automatic map height inference in JupyterLab so that the map will fill all available height when using sidecar. Hopefully this will let us customize what defaults to set where in a way that works everywhere 🤷‍♂️

Deduce environment and set map height in colab and vscode

---

README.md
build.mjs
docs/api/basemap.md
lonboard/_map.py
lonboard/basemap.py
mkdocs.yml
package-lock.json
package.json
src/accessor.ts
src/index.tsx
src/model/base.ts
src/model/extension.ts
src/model/index.ts
src/model/layer.ts
src/tooltip/index.ts
tsconfig.json

- Add `basemap_style` attribute
- Add enum with carto styles (closes https://github.com/developmentseed/lonboard/issues/265)
- Change tsconfig to use nodenext module resolution
- Explore bundle splitting to load maplibre-gl separately, but didn't work out of the box 😕 Ref https://visgl.github.io/react-map-gl/docs/api-reference/map#maplib

Add various carto basemaps as options

---

docs/alternatives.md

closes https://github.com/developmentseed/lonboard/issues/256

add keplergl-jupyter section to the docs

---

src/tooltip/index.ts

Previously, the falsy check didn't display a tooltip for the first row, where the `Symbol.for("rowIndex")` was 0.

Fix displaying tooltip for first row

---

docs/api/traits.md
lonboard/_layer.py
lonboard/_viewport.py
lonboard/_viz.py
lonboard/experimental/_layer.py
lonboard/traits.py
mkdocs.yml
poetry.lock
pyproject.toml

- Check for Arrow PyCapsule interface methods on input data, both in `viz` and in each layer type
- Add examples for passing GeoArrow table into layer
- Add docstrings for `table` attribute
- Validate that the computed center is in wgs84 bounds
- Add `PyarrowTableTrait` to docs page on traits
- Add auto-light/dark to docs website

Improved GeoArrow interop

---

lonboard/_layer.py
lonboard/_map.py
lonboard/_viewport.py
tests/test_layer.py

This adds a check on layer creation that the computed centroid of the input data is within the bounds of wgs84. This doesn't check the computed _bounding box_ because that could wrap over the international date line and have values less than -180.
This is improved over the previous approach because previously we checked the _final average_ of the centroid against wgs84, whereas now we check each layer individually. This is safer in case _most_ layers are wgs84 but one is not. Also, it errors at layer creation, which is a much better time to error.
In the future, we could allow web-mercator coordinates as well (see https://deck.gl/docs/developer-guide/coordinate-systems) and this would have to be refactored to allow the larger range of coordinates.

Check epsg:4326 bounds in layer creation

---

docs/api/layers/arc-layer.md
docs/api/layers/base-layer.md
docs/api/layers/bitmap-layer.md
docs/api/layers/bitmap-tile-layer.md
docs/api/layers/heatmap-layer.md
docs/api/layers/path-layer.md
docs/api/layers/scatterplot-layer.md
docs/api/layers/solid-polygon-layer.md
docs/api/layers/text-layer.md
docs/api/map.md
lonboard/__init__.py
lonboard/_layer.py
lonboard/_map.py
mkdocs.yml
tests/test_map.py

- Allow one or more `BaseLayer` objects to be passed into the first positional `Map` argument
- Update documentation
- Add docs page for base classes (`BaseLayer` and `BaseArrowLayer`)
- Add missing docs pages for `BitmapLayer` and `BitmapTileLayer`

Allow passing a positional `layers` object into `Map`

---

lonboard/_layer.py
lonboard/experimental/_layer.py
tests/test_traits.py

We use the `_rows_per_chunk` attribute to determine the number of rows that are included in each Parquet chunk sent to the frontend. This is a _layer-level_ construct because we need to ensure the main table and all accessors have exactly the same chunking, because each chunk is rendered independently as a separate deck.gl layer
We previously had issues where the number of rows per chunk was either not the same across all data objects within a layer, or alternatively a few cases (as with the ArcLayer) where we were accidentally initializing the number of rows per chunk to be `0`, which let to an infinite loop in `table.to_batches(max_chunksize=0)`.

Fix inferring number of rows per chunk

---

.pre-commit-config.yaml
docs/api/layer-extensions/brushing-extension.md
docs/api/layer-extensions/data-filter-extension.md
docs/api/layer-extensions/index.md
docs/api/layers/arc-layer.md
examples/migration.ipynb
lonboard/_base.py
lonboard/_layer.py
lonboard/_map.py
lonboard/_serialization.py
lonboard/_utils.py
lonboard/experimental/__init__.py
lonboard/experimental/layer_extension.py
mkdocs.yml
src/model/base-layer.ts
src/model/base.ts
src/model/extension.ts
src/model/index.ts
src/model/layer.ts

Connects to the deck.gl data filter extension ([example](https://deck.gl/examples/data-filter-extension), [docs](https://deck.gl/docs/api-reference/extensions/data-filter-extension)) for easy gpu-based data filtering.

Data filter extension

---

lonboard/_layer.py
lonboard/experimental/_layer.py
lonboard/experimental/layer_extension.py
src/model/base-layer.ts
src/model/layer.ts

Previously we had never been passing on falsy values to the deck.gl layer. Now, we try to be more consistent about initializing values to `None`, which get converted to `null` on the JS side. Then we check explicitly for `null` before passing values to deck layers.
Closes https://github.com/developmentseed/lonboard/issues/274

Fix null checks

---

lonboard/_serialization.py

Set the maximum number of separate chunks/row groups to allow splitting an input layer into.
Deck.gl can pick from a maximum of 256 layers, and a user could have many layers, so we don't want to use too many layers per data file.
This is for https://github.com/developmentseed/lonboard/issues/282 though isn't a complete solution, because many separate user-facing layers could still add up to more than 256 pickable deck layers.

Set max number of chunks per layer

---

lonboard/_layer.py
lonboard/_serialization.py
lonboard/experimental/_layer.py
tests/test_layer.py
tests/test_traits.py

Closes https://github.com/developmentseed/lonboard/issues/329
Currently we validate accessor length in `_validate_accessor_length` on the layer itself, but that's probably not able to dynamically validate all accessors, even those added by an extension. Instead, we can check during serialization that the length of the column is the same as the length of the table.
This additionally adds a test that accessor length validation is checked for extension accessors

Move accessor length validation to serialization

---

lonboard/_serialization.py
lonboard/experimental/traits.py
lonboard/traits.py

Previously, we had two copies of serialization that were doing essentially the same thing. 
This deduplicates accessor serialization to allow any "json-serializable" value through (a superset technically; whatever ipywidgets default serialization supports) but then otherwise assume the input is a pyarrow column and serialize that to a parquet file.

Deduplicate serialization for accessors

---

docs/api/experimental/traits.md
lonboard/experimental/layer_extension.py
lonboard/experimental/traits.py
src/model/extension.ts
tests/test_traits.py

Filter on up to 4 numeric attributes at the same time! This is working locally, but I need to figure out a clean way to connect it to the filter_value, since that's a list of lists.
The best solution (to enable jslink) might be to create our own custom widget that can display 1-4 float sliders and stores its value as a list of lists?

Multi-dimensional GPU-based data filtering

---

lonboard/_geoarrow/extension_types.py
lonboard/_geoarrow/geopandas_interop.py
lonboard/_geoarrow/ops/__init__.py
lonboard/_geoarrow/ops/reproject.py
lonboard/_layer.py
lonboard/_utils.py
poetry.lock
pyproject.toml
tests/test_geoarrow.py

- Include PROJJSON CRS on geometry array metadata when converting from GeoPandas
- Move CRS checking and reprojection into GeoArrow level instead of GeoPandas level
Low level example and benchmark. 4.6x reprojection speedup across 8 threads!
```py
import geodatasets
import pyarrow as pa
import geopandas as gpd
import numpy as np
from lonboard._geoarrow.geopandas_interop import geopandas_to_geoarrow
from lonboard._geoarrow.ops import reproject
path = geodatasets.get_path('nybb')
gdf = gpd.read_file(path)
table = geopandas_to_geoarrow(gdf)
field = table.schema.field(4)
column = table['geometry']
chunk = column.chunk(0)
new_chunked_array = pa.chunked_array([chunk] * 100)
%timeit out = reproject(field, new_chunked_array, max_workers=8)
%timeit out = reproject(field, new_chunked_array, …
```

geoarrow-based multithreaded coordinate reprojection

---

docs/api/controls.md
lonboard/__init__.py
lonboard/controls.py
lonboard/experimental/layer_extension.py
mkdocs.yml
pyproject.toml

Closes #339 
- Add `MultiRangeSlider`, a subclass of `ipywidgets.VBox` to connect multiple float range sliders
- Add to API docs

Multi-range sliders for DataFilterExtension

---

package-lock.json
package.json

Maplibre v4 breaks the basemap in the static HTML export

Downgrade maplibre to <4

---

lonboard/experimental/_layer.py

The arc layer was accidentally [rendering "flat" lines](https://deck.gl/docs/api-reference/layers/arc-layer#getheight) by default because we were unintentionally passing `0` as a default value. Instead we pass in `None` to "unset" a default value

fix arc layer default arguments

---

lonboard/_map.py

Thanks to @vincentsarago for leading me in the right direction!
Closes https://github.com/developmentseed/lonboard/issues/247

Set exported HTML height to 100%

---

lonboard/_geoarrow/ops/reproject.py
tests/test_geoarrow.py

When operating on _sliced_ input, the physical offsets are incorrect because the current array points to a range not at the beginning of the array. So when creating new arrays that are not sliced, we need to subtract off the original offset of the first element.
This is the primary bug from https://github.com/developmentseed/lonboard/issues/390

Fix: fix sliced array input for reprojection

---

lonboard/_geoarrow/ops/reproject.py

Previously I had accidentally been reprojecting 4326 input because I was checking against the OGC_84 definition and not also EPSG_4326

Fix: Don't reproject for epsg:4326 input

---

lonboard/_cli.py
lonboard/_geoarrow/ops/centroid.py

The third bug found when looking into https://github.com/developmentseed/lonboard/issues/390. 
I can't believe I'd never hit this before, but I was using the x coordinate values to update the _y_ value of the weighted centroid. So you'd potentially get this error for any large datasets in the western hemisphere.

Fix: Fix weighted centroid calculation

---

lonboard/_geoarrow/parse_wkb.py
tests/test_geoarrow.py

Closes https://github.com/developmentseed/lonboard/issues/406
This should allow a two-liner for visualization of just
```py
table = pyarrow.parquet.read_table('file.parquet')
lonboard.viz(table)
```

Parse GeoParquet metadata

---

lonboard/_cli.py

GeoParquet spec allows crs to be optional in the metadata. If missing don't pass it through the GeoArrow metadata.
Tested with a geoparquet file with a missing crs. Displays it with this fix.

CLI: 'crs' in geoparquet metadata should be optional.

---

docs/api/map.md
lonboard/_map.py
lonboard/_serialization.py
lonboard/_viewport.py
lonboard/models.py
lonboard/traits.py
src/actions/fly-to.ts
src/index.tsx
src/model/layer.ts
src/state.ts
src/util.ts

Closes https://github.com/developmentseed/lonboard/issues/112
In https://github.com/developmentseed/lonboard/pull/444 @batpad mentioned 
> It does seem to make the map a bit slow for me, and we should investigate that, but in principle, this for me works as expected
While playing around with that PR, I also saw some view state lagging at low zooms with lots of data rendered. In this screencast I'm smoothly zooming in, but the rendering is very jagged, and sometimes zooms back out slightly. **This screencast is of the previous PR**
https://github.com/developmentseed/lonboard/assets/15164633/bbe0a168-b76e-4563-bc30-828d648210db
My hypothesis of what's happening is that when rendering lots of data there's a slight lag for deck to call the `onViewStateChange` handler. And so deck will …

Sync view state between JS and Python

---

CHANGELOG.md
pyproject.toml
src/parquet.ts

- Lonboard 0.9 is totally broken because the parquet-wasm JS version and the parquet-wasm WASM version didn't match 😭

Fix parquet-wasm WASM version mismatch

---

lonboard/_geoarrow/_duckdb.py
lonboard/_geoarrow/extension_types.py
lonboard/_geoarrow/ops/coord_layout.py
lonboard/_geoarrow/ops/reproject.py
lonboard/traits.py

See https://stackoverflow.com/questions/28930465/what-is-the-difference-between-flatten-and-ravel-functions-in-numpy
Closes https://github.com/developmentseed/lonboard/issues/509.

Perf: Use ravel, not flatten, for numpy to pyarrow

---

examples/migration.ipynb

- Remove `layers=` keyword arg passing
- Reformat notebook with ruff

Simplify migration example

---

lonboard/_geoarrow/parse_wkb.py
lonboard/_utils.py
tests/test_viz.py

- Layer order for objects with mixed geometry types
Changed list appending order for `split_mixed_gdf` and `parse_wkb_table` function from [`points`, `linestrings`, `polygons`] to [`polygons`, `linestrings`, `points`]
- Points and paths should be now plotted on top of polygon for better visibility.
Old:
New:
#513

Feat: reverse the layer order for automatically split geometry

---

mkdocs.yml
poetry.lock
pyproject.toml

Include the new features in the public mkdocstrings-python version that [previously were only available in the insiders build](https://mkdocstrings.github.io/python/changelog/#180-2024-01-08).
You can click on links in the function signature and the TOC on the right has colored badges!

Bump mkdocstrings version

---

lonboard/_map.py
src/index.tsx
src/model/base-layer.ts

This adds a `custom_attribution` property to the `Map` class and fix Maplibre CSS by adding an import. Contributes to:
- #436
- #545
To test, add the `custom_attribution` property to a Map instance as demonstrated in the API docs examples.
@kylebarron this is ready for review.

Fix attribution

---

package-lock.json
package.json
src/index.tsx
src/reducer/index.ts
src/reducer/selectors.ts
src/reducer/utils.ts
src/util.ts

This is based on the WIP PR https://github.com/developmentseed/lonboard/pull/417. As this introduces considerable changes, I wanted to discuss them first before adding them to the `bbox-map-select` branch.
My main goal in this PR is to fix the bbox drawing behavior. The current implementation relies on `useState` and `useMemo`, which are hard to get right due to racing conditions with the map state and do not scale well once we start working on other data management features on the map.
In this proposed approach, we use a reducer and selectors, decoupling the application logic from the component. While this introduces some boilerplate code, the Deck.gl map works more like a presentation layer, making it more maintainable and scalable in the long run.
The bbox drawing behavior seems to be …

Fix bbox map select feature

---

docs/api/layers/column-layer.md
lonboard/__init__.py
lonboard/_layer.py
lonboard/types/layer.py
mkdocs.yml
src/model/layer.ts

Closes https://github.com/developmentseed/lonboard/issues/543
We already had the column layer on the JS side; so this PR only adds the Python bindings + a docs page
From @cboettig 's example in the above issue:
```py
import geopandas as gpd
DATA_URL = 'https://data.source.coop/cboettig/conservation-policy/Inflation_Reduction_Act_Projects.geojson'
df = gpd.read_file(DATA_URL)
layer = ColumnLayer.from_geopandas(
df, 
get_elevation=df["FUNDING_NUMERIC"], 
get_fill_color = [255, 255, 0, 140],
elevation_scale=.01,
radius=10000,
pickable=True,
auto_highlight=True,
)
m = Map(
layer,
view_state={"longitude": -100, "latitude": 35, "zoom": 4, "pitch": 45, "bearing": 0},
)
m
```

Add `ColumnLayer`

---

lonboard/_constants.py
lonboard/_geoarrow/parse_wkb.py
lonboard/_geoarrow/utils.py
lonboard/_layer.py
lonboard/_viz.py
tests/test_viz.py

- We already look for `geoarrow.wkb` (and `geoarrow.ogc_wkb`) extension names in the input table and parse those WKB columns. 
- For parity with WKB, we also check for `geoarrow.wkt`, and parse it to native coords

Parse `geoarrow.wkt` serialized data type in input

---

lonboard/_constants.py

In pyodide, the pyproj PROJ data directory is much smaller, and it currently
hard-crashes on the line `pyproj.CRS("ogc:84")`. Instead, we vendor the PROJJSON
representation of this CRS, which works in pyodide.

Store the PROJJSON representation of ogc-84 crs

---

lonboard/_base.py
lonboard/_geoarrow/ops/coord_layout.py
lonboard/_layer.py
lonboard/traits.py
tests/test_layer.py
tests/test_traits.py

- Rechunk all non-scalar accessor data to match the chunking of the main table.
- All Arrow accessors are stored as `arro3.core.ChunkedArray`. Bare arrays are never stored.
Closes https://github.com/developmentseed/lonboard/issues/611
cc @abarciauskas-bgse since you commented on https://github.com/developmentseed/lonboard/issues/611

Manage arrow rechunking

---

examples/overture-maps.ipynb
poetry.lock

Closes https://github.com/developmentseed/lonboard/issues/482, originally fixed by https://github.com/developmentseed/lonboard/pull/644

Remove arrow workaround from overture maps example

---

lonboard/_layer.py
lonboard/_map.py
lonboard/experimental/_layer.py
lonboard/layer_extension.py

Just a stylistic choice because we're using `traitlets.*` often in our code, and I don't want to bring all of the traitlets objects into global scope.

`import traitlets as t`

---

lonboard/_layer.py
lonboard/_map.py
src/index.tsx

`selected_bounds` should be a property of the **Map**. In the future, when we use deck.gl to perform picking, we'll have `selected_indices` as a property of each _individual layer_. This is necessary because the data is a property of each layer, while 
Or alternatively if we perform data filtering on the Python side, then in the future we could also add `selected_bounds` to each layer (though probably as a private attribute)

Move `selected_bounds` from `Layer` to `Map`

---

CHANGELOG.md
docs/ecosystem/pyodide.md
examples/internet-speeds.ipynb
pyproject.toml
src/index.tsx

- Updated changelog
- Added `model.save_changes` that was left out from https://github.com/developmentseed/lonboard/pull/676
- Minor other fixes

Bump to 0.10

---

lonboard/_map.py

Closes https://github.com/developmentseed/lonboard/issues/725#issuecomment-2572885038
Avoids including the data from _all_ previous widgets.

Pass state in `to_html`

---

lonboard/_map.py

use dependency state in export

---

lonboard/_geoarrow/_duckdb.py
tests/test_duckdb.py

Fix sanity check of `geom_col_name` to actually check the whole string.
`re.match(re_match)` was matching any string containing _any_ `[a-zA-Z]` character, regardless of the rest.
The solution is `re.fullmatch()`. Another way would have been to append `r"^...$"` to the beginning and end of `re_match`.
Wrote test `test_sanitize_column_name()`.
Closes #768
In general, the issue of [hardcoded-sql-expression](https://github.com/developmentseed/lonboard/blob/98d68f750ece7d09e209edba354e124ceb3416d5/lonboard/_geoarrow/_duckdb.py#L1) is still out there.

Sanitize geomcolname

---

.pre-commit-config.yaml

the possible value for `default_stages` is now called "pre-commit", according to https://pre-commit.com/#pre-commit-configyaml---top-level and the warning put out by `pre-commit==4.1.0` when using legacy "commit":
```bash
$ pre-commit run
[WARNING] top-level `default_stages` uses deprecated stage names (commit) which will be removed in a future version.  run: `pre-commit migrate-config` to automatically fix this.
```

follow stage rename in pre-commit config

---

lonboard/_viz.py

as the previous code snippet line already includes an example table name ("spatial_table"), I suggest to include this in the `viz()` call below for continuity, clarity (even though I understand that these examples are not complete running code, again for clarity).
(or at least it should be `con.table(...)` to follow the pattern of ellipses in the previous line, to make it clear it is not a function call without parameters)

include table name in con.table() example

---

lonboard/_layer.py

- Allow passing `table` as positional arg
- Add docstring for `BaseArrowLayer.__init__` so it shows up in docs.
Closes https://github.com/developmentseed/lonboard/issues/695

feat: Allow passing Arrow table as positional argument to layer constructors

---

mkdocs.yml

Linking now works:
Closes https://github.com/developmentseed/lonboard/issues/774

docs: Add duckdb intersphinx mapping

---

docs/how-it-works/index.md

Closes https://github.com/developmentseed/lonboard/issues/785

docs: Reword section in "How it works" to reflect GeoParquet 1.1

---

lonboard/_geoarrow/_duckdb.py

to avoid duckdb becoming a hard dependency
move import to inside function
might trigger a ruff rule around imports not at top of file
closes #810 
(or alternatively, duckdb should explicitly become a hard dependency)

fix: move duckdb imports to inside function

---

lonboard/_geoarrow/ops/bbox.py
lonboard/_geoarrow/ops/centroid.py
lonboard/_geoarrow/ops/coord_layout.py
lonboard/_geoarrow/row_index.py
lonboard/_layer.py
lonboard/_viz.py
lonboard/traits.py
pyproject.toml
tests/test_box.py
uv.lock

- Implement `total_bounds` and `weighted_centroid` for `geoarrow.box` arrays
- Always add positional row index when the user passes in a raw array or chunked array
- Convert a geoarrow box column to a geoarrow polygon column in the table trait validation directly.
- Add new tests for passing `geoarrow.box` array and chunked array into `PolygonLayer` constructor.
Closes https://github.com/developmentseed/lonboard/issues/823

feat: Allow passing GeoArrow arrays and chunked arrays directly to layer constructors

---

examples/air-traffic-control.ipynb
examples/ais-movingpandas.ipynb
examples/internet-speeds.ipynb
examples/map_challenge/1-points.ipynb
examples/overture-geoparquet.ipynb

Updated the examples to reference `height` of maps now that it has replaced `_height`
closes #849

docs: Update examples referencing '_height'

---

CHANGELOG.md
lonboard/_viz.py

I need to make a new release of Lonboard so that I can make a demo for Monday. And we need support for passing geoarrow geometry columns to a visualization

chore: Prepare 0.12 release

---

lonboard/_geoarrow/ops/coord_layout.py
lonboard/experimental/_layer.py
lonboard/traits.py
lonboard/types/layer.py
tests/layers/test_arc_layer.py

Closes https://github.com/developmentseed/lonboard/issues/869

feat: Support struct GeoArrow input for ArcLayer positions

---

mkdocs.yml

Turns out mkdocs-jupyter is clobbering the marimo example added in #881

docs: Don't run mkdocs-jupyter on py files
